server:
  port: ":8080"

database:
  host: "localhost"
  port: 5432
  user: "root"
  password: 123
  dbname: "marketplace"
  sslmode: "disable"

auth:
  secretKey: abcdefgh
  accessTokenTTL: 86400000000000
  refreshTokenTTL: 2592000000000000
